# **CARGA DE DATASET**

In [35]:
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import RFECV
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import KFold, cross_val_score

df = pd.read_csv('/content/drive/MyDrive/DataSets/smoking_driking_dataset_Ver02_r.csv')
print(df.head(5))

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
      sex  age  height  weight  waistline  sight_left  sight_right  hear_left  \
0  Female   50     155      60       82.0         0.7          0.5        1.0
1  Female   55     155      50       73.2         1.0          0.8        1.0
2  Female   60     160      60       78.0         0.6          0.8        1.0
3    Male   35     175      80       94.0         1.2          1.2        1.0
4    Male   45     160      60       82.1         0.9          0.8        1.0

   hear_right    SBP  ...  LDL_chole  triglyceride  hemoglobin  urine_protein  \
0         1.0  130.0  ...       95.0         193.0        14.0            1.0
1         1.0  115.0  ...      132.0          39.0        12.9            1.0
2         1.0   97.0  ...       90.0          57.0        13.3            1.0
3         1.0  121.0  ...      128.0         258.0        15.3            1.0
4         1.0  135.0  ...       99.0         115.0        14.8            1.0

   serum_creatinine  SGOT_AST  SGOT_ALT  gamma_GTP  SMK_stat_type_cd  DRK_YN
0               0.7      30.0      26.0       35.0               1.0       Y
1               0.6      25.0      18.0       14.0               1.0       N
2               0.7      21.0      16.0       11.0               1.0       N
3               0.6      19.0      27.0       31.0               3.0       Y
4               0.9      17.0      28.0       48.0               1.0       Y

[5 rows x 24 columns]

In [36]:
df.shape

(10204, 24)

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10204 entries, 0 to 10203
Data columns (total 24 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   sex               10204 non-null  object
 1   age               10204 non-null  int64
 2   height            10204 non-null  int64
 3   weight            10204 non-null  int64
 4   waistline         10204 non-null  float64
 5   sight_left        10204 non-null  float64
 6   sight_right       10204 non-null  float64
 7   hear_left         10200 non-null  float64
 8   hear_right        10203 non-null  float64
 9   SBP               10204 non-null  float64
 10  DBP               10204 non-null  float64
 11  BLDS              10204 non-null  float64
 12  tot_chole         10204 non-null  float64
 13  HDL_chole         10204 non-null  float64
 14  LDL_chole         10204 non-null  float64
 15  triglyceride      10204 non-null  float64
 16  hemoglobin        10204 non-null  float64
 17  urine_protein     10196 non-null  float64
 18  serum_creatinine  10204 non-null  float64
 19  SGOT_AST          10204 non-null  float64
 20  SGOT_ALT          10204 non-null  float64
 21  gamma_GTP         10204 non-null  float64
 22  SMK_stat_type_cd  10203 non-null  float64
 23  DRK_YN            10204 non-null  object
dtypes: float64(19), int64(3), object(2)
memory usage: 1.9+ MB



*   Obtener los valores únicos y su tamaño
*   Contar la frecuencia de cada valor único
*   Mostrar los valores únicos

In [19]:
col = 'sex'
unique_values = df[col].unique()
print(unique_values.size)
print(df[col].value_counts())
print(unique_values)

2
sex
Male      5421
Female    4783
Name: count, dtype: int64
['Female' 'Male']

In [39]:
col = 'DRK_YN'
unique_values = df[col].unique()
print(unique_values.size)
print(df[col].value_counts())
print(unique_values)

2
DRK_YN
N    5180
Y    5024
Name: count, dtype: int64
['Y' 'N']

# **•	Descripción de atributos**
* Sexo (sex). Descripción: Sexo del individuo. Tipo de Atributo: **Nominal**. Tipo de Dato: **object**. Valores Nulos: No.
* Edad (age). Descripción: Edad redondeada en intervalos de 5 años. Tipo de Atributo: **Intervalo**. Tipo de Dato: **int64**. Valores Nulos: No.
* Altura (height). Descripción: Altura redondeada en intervalos de 5 cm [cm]. Tipo de Atributo: **Intervalo**. Tipo de Dato: **int64**. Valores Nulos: No.
* Peso (weight). Descripción: Peso en kilogramos [kg]. Tipo de Atributo: **Intervalo**. Tipo de Dato: **int64**. Valores Nulos: No.
* Circunferencia de Cintura (waistline). Descripción: Circunferencia de la cintura en centímetros. Tipo de Atributo: **Ratio**. Tipo de Dato: **float64**. Valores Nulos: No.
* Vista Izquierda (sight_left). Descripción: Agudeza visual del ojo izquierdo. Tipo de Atributo: **Ratio**. Tipo de Dato: **float64**. Valores Nulos: No.
* Vista Derecha (sight_right). Descripción: Agudeza visual del ojo derecho. Tipo de Atributo: **Ratio**. Tipo de Dato: **float64**. Valores Nulos: No.
* Audición Izquierda (hear_left). Descripción: Capacidad auditiva del oído izquierdo (1 = normal, 2 = anormal). Tipo de Atributo: **Nominal**. Tipo de Dato: **float64**. Valores Nulos: Sí, 4 valores nulos.
* Audición Derecha (hear_right). Descripción: Capacidad auditiva del oído derecho (1 = normal, 2 = anormal). Tipo de Atributo: **Nominal**. Tipo de Dato: **float64**. Valores Nulos: Sí, 1 valor nulo.
* Presión Arterial Sistólica (SBP). Descripción: Presión arterial sistólica [mmHg]. Tipo de Atributo: **Ratio**. Tipo de Dato: **int64**. Valores Nulos: No.
* Presión Arterial Diastólica (DBP). Descripción: Presión arterial diastólica [mmHg]. Tipo de Atributo: **Ratio**. Tipo de Dato: **int64**. Valores Nulos: No.
* Glucosa en Sangre en Ayunas (BLDS). Descripción: Glucosa en sangre en ayunas [mg/dL]. Tipo de Atributo: **Ratio**. Tipo de Dato: **int64**. Valores Nulos: No.
* Colesterol Total (tot_chole). Descripción: Colesterol total [mg/dL]. Tipo de Atributo: **Ratio**. Tipo de Dato: **int64**. Valores Nulos: No.
* Colesterol HDL (HDL_chole). Descripción: Colesterol HDL [mg/dL]. Tipo de Atributo: **Ratio**. Tipo de Dato: **int64**. Valores Nulos: No.
* Colesterol LDL (LDL_chole). Descripción: Colesterol LDL [mg/dL]. Tipo de Atributo: **Ratio**. Tipo de Dato: **int64**. Valores Nulos: No.
* Triglicéridos (triglyceride). Descripción: Triglicéridos [mg/dL]. Tipo de Atributo: **Ratio**. Tipo de Dato: **int64**. Valores Nulos: No.
* Hemoglobina (hemoglobin). Descripción: Hemoglobina [g/dL]. Tipo de Atributo: **Ratio**. Tipo de Dato: **float64**. Valores Nulos: No.
* Proteína en Orina (urine_protein). Descripción: Proteína en orina (1 = -, 2 = +/-, 3 = +1, 4 = +2, 5 = +3, 6 = +4). Tipo de Atributo: **Ordinal**. Tipo de Dato: **float64**. Valores Nulos: Sí, 8 valores nulos.
* Creatinina Sérica (serum_creatinine). Descripción: Creatinina sérica [mg/dL]. Tipo de Atributo: **Ratio**. Tipo de Dato: **float64**. Valores Nulos: No.
* SGOT (AST) (SGOT_AST). Descripción: SGOT (Glutamato-oxalacetato transaminasa) AST (Aspartato transaminasa) [UI/L]. Tipo de Atributo: **Ratio**. Tipo de Dato: **int64**. Valores Nulos: No.
* SGOT (ALT) (SGOT_ALT). Descripción: ALT (Alanina transaminasa) [UI/L]. Tipo de Atributo: **Ratio**. Tipo de Dato: **int64**. Valores Nulos: No.
* Gamma-GTP (gamma_GTP). Descripción: Gamma-glutamil transpeptidasa [UI/L]. Tipo de Atributo: **Ratio**. Tipo de Dato: **int64**. Valores Nulos: No.
* Estado de Fumar (SMK_stat_type_cd). Descripción: Estado de fumar (1 = nunca, 2 = solía fumar pero lo dejó, 3 = todavía fuma). Tipo de Atributo: **Nominal**. Tipo de Dato: **float64**. Valores Nulos: Sí, 1 valor nulo.
* Bebedor o No (DRK_YN). Descripción: Bebedor o no. Tipo de Atributo: **Nominal**. Tipo de Dato: **object**. Valores Nulos: No.

# **Tratamiento de Valores Faltantes**

---



* Técnica Utilizada: Imputación por la moda (valor más frecuente).
* Técnica Utilizada: Imputación por la mediana.

In [40]:
# Tratamiento de valores faltantes
for column in ['hear_left', 'hear_right', 'SMK_stat_type_cd']:
    mode_value = df[column].mode()[0]
    df[column].fillna(mode_value, inplace=True)

median_value = df['urine_protein'].median()
df['urine_protein'].fillna(median_value, inplace=True)

In [41]:
df.isnull().sum()

sex                 0
age                 0
height              0
weight              0
waistline           0
sight_left          0
sight_right         0
hear_left           0
hear_right          0
SBP                 0
DBP                 0
BLDS                0
tot_chole           0
HDL_chole           0
LDL_chole           0
triglyceride        0
hemoglobin          0
urine_protein       0
serum_creatinine    0
SGOT_AST            0
SGOT_ALT            0
gamma_GTP           0
SMK_stat_type_cd    0
DRK_YN              0
dtype: int64

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10204 entries, 0 to 10203
Data columns (total 24 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   sex               10204 non-null  object
 1   age               10204 non-null  int64
 2   height            10204 non-null  int64
 3   weight            10204 non-null  int64
 4   waistline         10204 non-null  float64
 5   sight_left        10204 non-null  float64
 6   sight_right       10204 non-null  float64
 7   hear_left         10204 non-null  float64
 8   hear_right        10204 non-null  float64
 9   SBP               10204 non-null  float64
 10  DBP               10204 non-null  float64
 11  BLDS              10204 non-null  float64
 12  tot_chole         10204 non-null  float64
 13  HDL_chole         10204 non-null  float64
 14  LDL_chole         10204 non-null  float64
 15  triglyceride      10204 non-null  float64
 16  hemoglobin        10204 non-null  float64
 17  urine_protein     10204 non-null  float64
 18  serum_creatinine  10204 non-null  float64
 19  SGOT_AST          10204 non-null  float64
 20  SGOT_ALT          10204 non-null  float64
 21  gamma_GTP         10204 non-null  float64
 22  SMK_stat_type_cd  10204 non-null  float64
 23  DRK_YN            10204 non-null  object
dtypes: float64(19), int64(3), object(2)
memory usage: 1.9+ MB

# **Convertir atributos categóricos a numéricos usando Codificación One-Hot**

*  crean nuevas columnas binarias para representar las categorías de la columna original sex_Female	, sex_Male
* valores 0,1

In [43]:
df = pd.get_dummies(df, columns=['sex'], dtype=int)
df

,age,height,weight,waistline,sight_left,sight_right,hear_left,hear_right,SBP,DBP,...,hemoglobin,urine_protein,serum_creatinine,SGOT_AST,SGOT_ALT,gamma_GTP,SMK_stat_type_cd,DRK_YN,sex_Female,sex_Male
0,50,155,60,82.0,0.7,0.5,1.0,1.0,130.0,86.0,...,14.0,1.0,0.7,30.0,26.0,35.0,1.0,Y,1,0
1,55,155,50,73.2,1.0,0.8,1.0,1.0,115.0,67.0,...,12.9,1.0,0.6,25.0,18.0,14.0,1.0,N,1,0
2,60,160,60,78.0,0.6,0.8,1.0,1.0,97.0,66.0,...,13.3,1.0,0.7,21.0,16.0,11.0,1.0,N,1,0
3,35,175,80,94.0,1.2,1.2,1.0,1.0,121.0,79.0,...,15.3,1.0,0.6,19.0,27.0,31.0,3.0,Y,0,1
4,45,160,60,82.1,0.9,0.8,1.0,1.0,135.0,88.0,...,14.8,1.0,0.9,17.0,28.0,48.0,1.0,Y,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10199,60,155,75,94.0,1.2,0.9,1.0,1.0,151.0,85.0,...,13.4,1.0,0.6,45.0,49.0,44.0,1.0,N,1,0
10200,30,160,75,88.0,0.3,0.4,1.0,1.0,131.0,69.0,...,13.2,1.0,0.8,25.0,27.0,31.0,1.0,N,1,0
10201,25,160,60,70.0,1.2,1.2,1.0,1.0,110.0,70.0,...,13.8,1.0,0.6,19.0,17.0,23.0,1.0,N,1,0
10202,55,165,65,73.0,1.0,1.0,1.0,1.0,142.0,88.0,...,15.0,1.0,0.8,25.0,19.0,45.0,2.0,N,0,1
10203,75,165,65,88.0,0.4,1.0,1.0,1.0,130.0,65.0,...,14.2,1.0,1.1,19.0,21.0,38.0,2.0,Y,0,1


* OrdinalEncoder para convertir 'DRK_YN' en números ordinales
*

In [45]:
from sklearn.preprocessing import OrdinalEncoder
print(df['DRK_YN'].unique())
print(df['DRK_YN'].value_counts())
encoder = OrdinalEncoder()
df['DRK_YN'] = encoder.fit_transform(df[['DRK_YN']])
print(df['DRK_YN'].unique())
df

[1. 0.]
DRK_YN
0.0    5180
1.0    5024
Name: count, dtype: int64
[1. 0.]

,age,height,weight,waistline,sight_left,sight_right,hear_left,hear_right,SBP,DBP,...,hemoglobin,urine_protein,serum_creatinine,SGOT_AST,SGOT_ALT,gamma_GTP,SMK_stat_type_cd,DRK_YN,sex_Female,sex_Male
0,50,155,60,82.0,0.7,0.5,1.0,1.0,130.0,86.0,...,14.0,1.0,0.7,30.0,26.0,35.0,1.0,1.0,1,0
1,55,155,50,73.2,1.0,0.8,1.0,1.0,115.0,67.0,...,12.9,1.0,0.6,25.0,18.0,14.0,1.0,0.0,1,0
2,60,160,60,78.0,0.6,0.8,1.0,1.0,97.0,66.0,...,13.3,1.0,0.7,21.0,16.0,11.0,1.0,0.0,1,0
3,35,175,80,94.0,1.2,1.2,1.0,1.0,121.0,79.0,...,15.3,1.0,0.6,19.0,27.0,31.0,3.0,1.0,0,1
4,45,160,60,82.1,0.9,0.8,1.0,1.0,135.0,88.0,...,14.8,1.0,0.9,17.0,28.0,48.0,1.0,1.0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10199,60,155,75,94.0,1.2,0.9,1.0,1.0,151.0,85.0,...,13.4,1.0,0.6,45.0,49.0,44.0,1.0,0.0,1,0
10200,30,160,75,88.0,0.3,0.4,1.0,1.0,131.0,69.0,...,13.2,1.0,0.8,25.0,27.0,31.0,1.0,0.0,1,0
10201,25,160,60,70.0,1.2,1.2,1.0,1.0,110.0,70.0,...,13.8,1.0,0.6,19.0,17.0,23.0,1.0,0.0,1,0
10202,55,165,65,73.0,1.0,1.0,1.0,1.0,142.0,88.0,...,15.0,1.0,0.8,25.0,19.0,45.0,2.0,0.0,0,1
10203,75,165,65,88.0,0.4,1.0,1.0,1.0,130.0,65.0,...,14.2,1.0,1.1,19.0,21.0,38.0,2.0,1.0,0,1

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10204 entries, 0 to 10203
Data columns (total 25 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   age               10204 non-null  int64
 1   height            10204 non-null  int64
 2   weight            10204 non-null  int64
 3   waistline         10204 non-null  float64
 4   sight_left        10204 non-null  float64
 5   sight_right       10204 non-null  float64
 6   hear_left         10204 non-null  float64
 7   hear_right        10204 non-null  float64
 8   SBP               10204 non-null  float64
 9   DBP               10204 non-null  float64
 10  BLDS              10204 non-null  float64
 11  tot_chole         10204 non-null  float64
 12  HDL_chole         10204 non-null  float64
 13  LDL_chole         10204 non-null  float64
 14  triglyceride      10204 non-null  float64
 15  hemoglobin        10204 non-null  float64
 16  urine_protein     10204 non-null  float64
 17  serum_creatinine  10204 non-null  float64
 18  SGOT_AST          10204 non-null  float64
 19  SGOT_ALT          10204 non-null  float64
 20  gamma_GTP         10204 non-null  float64
 21  SMK_stat_type_cd  10204 non-null  float64
 22  DRK_YN            10204 non-null  float64
 23  sex_Female        10204 non-null  int64
 24  sex_Male          10204 non-null  int64
dtypes: float64(20), int64(5)
memory usage: 1.9 MB

# **Escalado o normalización**

Dado que los atributos son de tipo ratio y pueden tener diferentes escalas, escalaremos los datos usando StandardScaler.

In [47]:
# Escalado o normalización
scaler = StandardScaler()
scaled_data = scaler.fit_transform(df.drop('DRK_YN', axis=1))

# Crear un nuevo DataFrame con los datos escalados
scaled_df = pd.DataFrame(scaled_data, columns=df.columns[:-1])
scaled_df['DRK_YN'] = df['DRK_YN']

# **	Selección de atributos:  **

en este caso, todas las características podrían ser potencialmente relevantes para predecir la variable objetivo 'DRK_YN'.

In [62]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

X = scaled_df.drop('DRK_YN', axis=1)
y = scaled_df['DRK_YN']

logreg = LogisticRegression(solver='lbfgs', multi_class='auto', max_iter=1000)


selector = RFE(estimator=logreg, n_features_to_select=10, step=1)

selector = selector.fit(X, y)

print('Características seleccionadas:')
for i, feature in enumerate(X.columns):
    if selector.support_[i]:
        print(feature)

Características seleccionadas:
age
tot_chole
HDL_chole
LDL_chole
triglyceride
SGOT_AST
SGOT_ALT
gamma_GTP
SMK_stat_type_cd
sex_Female

In [56]:
X

,age,height,weight,waistline,sight_left,sight_right,hear_left,hear_right,SBP,DBP,...,LDL_chole,triglyceride,hemoglobin,urine_protein,serum_creatinine,SGOT_AST,SGOT_ALT,gamma_GTP,SMK_stat_type_cd,sex_Female
0,0.158452,-0.776344,-0.248078,0.064484,-0.456196,-0.776326,-0.184525,-0.181666,0.537927,1.035839,...,-0.510432,0.634641,-0.139139,-0.214346,-0.571057,0.233028,0.017422,-0.042398,-0.749593,-1.064607
1,0.509863,-0.776344,-1.057732,-0.604231,0.033103,-0.286792,-0.184525,-0.181666,-0.494644,-0.898717,...,0.555686,-0.945517,-0.838068,-0.214346,-0.935704,-0.056766,-0.340805,-0.443215,-0.749593,-1.064607
2,0.861274,-0.232786,-0.248078,-0.239478,-0.619295,-0.286792,-0.184525,-0.181666,-1.733728,-1.000535,...,-0.654502,-0.760823,-0.583912,-0.214346,-0.571057,-0.288601,-0.430361,-0.500474,-0.749593,-1.064607
3,-0.895781,1.397889,1.371231,0.976368,0.359301,0.365919,-0.184525,-0.181666,-0.081615,0.323108,...,0.440430,1.301591,0.686868,-0.214346,-0.935704,-0.404519,0.062200,-0.118744,1.695301,0.939313
4,-0.192959,-0.232786,-0.248078,0.072083,-0.129997,-0.286792,-0.184525,-0.181666,0.882117,1.239476,...,-0.395176,-0.165699,0.369173,-0.214346,0.158238,-0.520437,0.106978,0.205726,-0.749593,0.939313
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10199,0.861274,-0.776344,0.966404,0.976368,0.359301,-0.123615,-0.184525,-0.181666,1.983526,0.934020,...,1.016710,0.296036,-0.520373,-0.214346,-0.935704,1.102410,1.047322,0.129380,-0.749593,-1.064607
10200,-1.247192,-0.232786,0.966404,0.520426,-1.108593,-0.939504,-0.184525,-0.181666,0.606765,-0.695079,...,0.670942,0.439687,-0.647451,-0.214346,-0.206410,-0.056766,0.062200,-0.118744,-0.749593,-1.064607
10201,-1.598603,-0.232786,-0.248078,-0.847400,0.359301,0.365919,-0.184525,-0.181666,-0.838834,-0.593261,...,1.016710,-0.535086,-0.266217,-0.214346,-0.935704,-0.404519,-0.385583,-0.271436,-0.749593,-1.064607
10202,0.509863,0.310772,0.156750,-0.619429,0.033103,0.039563,-0.184525,-0.181666,1.363983,1.239476,...,0.872640,0.552555,0.496251,-0.214346,-0.206410,-0.056766,-0.296026,0.148466,0.472854,0.939313
10203,1.915507,0.310772,0.156750,0.520426,-0.945494,0.039563,-0.184525,-0.181666,0.537927,-1.102354,...,-0.049408,0.532034,-0.012061,-0.214346,0.887532,-0.404519,-0.206470,0.014861,0.472854,0.939313

In [50]:
y

0        1.0
1        0.0
2        0.0
3        1.0
4        1.0
        ...
10199    0.0
10200    0.0
10201    0.0
10202    0.0
10203    1.0
Name: DRK_YN, Length: 10204, dtype: float64

In [58]:

X_optimal = X.loc[:, selector.support_]

# **Modelo SVM**

In [59]:
# Modelo SVM
svm_model = SVC()
kf = KFold(n_splits=10, random_state=0, shuffle=True)
svm_scores = cross_val_score(svm_model, X_optimal, y, cv=kf, scoring='accuracy')
svm_accuracy = svm_scores.mean()
print(f'SVM Accuracy: {svm_accuracy}')

SVM Accuracy: 0.7183439918572719

# **Modelo Random Forest**

In [60]:
# Modelo Random Forest
rf_model = RandomForestClassifier()
rf_scores = cross_val_score(rf_model, X_optimal, y, cv=kf, scoring='accuracy')
rf_accuracy = rf_scores.mean()
print(f'Random Forest Accuracy: {rf_accuracy}')

Random Forest Accuracy: 0.7052144187743657